# Generated by Django 4.2.4 on 2025-12-14 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0005_product_rating_product_review_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealCountdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Top Deals Of The Day', max_length=100)),
                ('end_time', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
