# Generated by Django 4.2.4 on 2026-01-26 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0009_alter_product_options_product_slug_wishlist_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('TOP_DEALS', 'Top Deals Of The Day'), ('TOP_SELLING', 'Top Selling Products'), ('TOP_FEATURED', 'Top Featured Products'), ('RECOMMENDED', 'Recommended For You')], help_text='Select product category for homepage sections', max_length=20, null=True),
        ),
    ]
