# Generated by Django 4.2.4 on 2026-01-28 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0013_userprofile_customer_segment_userprofile_is_blocked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='customer_segment',
            field=models.CharField(choices=[('NEW', 'New Customer'), ('REGULAR', 'Regular Customer'), ('VIP', 'VIP Customer'), ('ADMIN', 'Admin User')], default='NEW', max_length=15),
        ),
    ]
