# Generated by Django 4.2.4 on 2026-01-28 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0015_productreview_helpful_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='descriptionImage',
            field=models.ImageField(blank=True, help_text='Large description image displayed below product description', null=True, upload_to='products/descriptions/'),
        ),
    ]
