# Generated by Django 4.2.4 on 2026-01-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0016_product_descriptionimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productquestion',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Show on product page only after admin approval and answer'),
        ),
    ]
