# Generated by Django 4.2.4 on 2026-01-28 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0017_alter_productquestion_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='background_color',
            field=models.CharField(blank=True, help_text='Optional background color overlay (e.g., rgba(255,0,0,0.1))', max_length=20),
        ),
        migrations.AddField(
            model_name='banner',
            name='badge_text',
            field=models.CharField(blank=True, help_text="Badge text like 'HOT DEALS' (optional)", max_length=50),
        ),
        migrations.AddField(
            model_name='banner',
            name='banner_type',
            field=models.CharField(choices=[('SMALL', 'Small Banner'), ('MEDIUM', 'Medium Banner'), ('LARGE', 'Large Banner')], default='LARGE', help_text='Banner size type', max_length=10),
        ),
        migrations.AddField(
            model_name='banner',
            name='button_style',
            field=models.CharField(choices=[('st-btn', 'Yellow Button (HOT DEALS)'), ('st-btn-3 b-radius', 'White Button (Shop Deals)'), ('none', 'No Button')], default='none', help_text='Select button style', max_length=20),
        ),
        migrations.AddField(
            model_name='banner',
            name='button_text',
            field=models.CharField(blank=True, help_text="Button text like 'Shop Deals' (optional)", max_length=50),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(help_text='Banner background image', upload_to='banners/'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='link_url',
            field=models.CharField(blank=True, default='#', help_text='URL to redirect when banner is clicked', max_length=200),
        ),
        migrations.AlterField(
            model_name='banner',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order (lower number = shown first)'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Subtitle or description (optional)', max_length=200),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(help_text='Main title/heading of the banner', max_length=200),
        ),
    ]
