# Generated by Django 4.2.4 on 2026-01-28 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0018_banner_background_color_banner_badge_text_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider',
            options={'ordering': ['order', '-id']},
        ),
        migrations.AddField(
            model_name='slider',
            name='order',
            field=models.IntegerField(default=0, help_text='Display order (lower numbers appear first)'),
        ),
    ]
