# Generated by Django 4.2.4 on 2026-01-28 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0019_alter_slider_options_slider_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='page_type',
            field=models.CharField(choices=[('HOME', 'Home Page'), ('SHOP', 'Shop Page'), ('BOTH', 'Both Home & Shop')], default='HOME', help_text='Which page to display this banner on', max_length=10),
        ),
    ]
