# Generated by Django 4.2.4 on 2026-01-28 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0020_banner_page_type'),
    ]

    operations = [
    ]
