# Generated by Django 4.2.4 on 2026-01-29 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0022_order_orderitem_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_resell',
            field=models.BooleanField(default=False, help_text='Is this a resell order?'),
        ),
        migrations.AddField(
            model_name='order',
            name='razorpay_order_id',
            field=models.CharField(blank=True, help_text='Razorpay Order ID', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, help_text='Razorpay Payment ID', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='razorpay_signature',
            field=models.CharField(blank=True, help_text='Razorpay Payment Signature', max_length=200),
        ),
    ]
