# Generated by Django 6.0.1 on 2026-01-29 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0023_order_is_resell_order_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='resell_from_name',
            field=models.CharField(blank=True, help_text='Original seller name for resell orders', max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='resell_from_phone',
            field=models.CharField(blank=True, help_text='Original seller phone for resell orders', max_length=20),
        ),
    ]
