# Generated by Django 4.2.4 on 2026-01-29 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0024_order_resell_from_name_order_resell_from_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('TOP_DEALS', 'Top Deals Of The Day'), ('TOP_SELLING', 'Top Selling Products'), ('TOP_FEATURED', 'Top Featured Products'), ('RECOMMENDED', 'Recommended For You'), ('MOBILES', 'Mobiles'), ('FOOD_HEALTH', 'Food & Health'), ('HOME_KITCHEN', 'Home & Kitchen'), ('AUTO_ACC', 'Auto Acc'), ('FURNITURE', 'Furniture'), ('SPORTS', 'Sports'), ('GENZ_TRENDS', 'GenZ Trends'), ('NEXT_GEN', 'Next Gen')], help_text='Select product category for homepage sections', max_length=20, null=True),
        ),
    ]
