# Generated by Django 4.2.4 on 2026-01-29 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0025_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name (e.g., Mobiles, Food & Health)', max_length=100)),
                ('icon_class', models.CharField(help_text="FontAwesome icon class (e.g., 'fas fa-mobile-alt')", max_length=100)),
                ('category_key', models.CharField(help_text="Category key matching Product.CATEGORY_CHOICES (e.g., 'MOBILES')", max_length=50, unique=True)),
                ('background_gradient', models.CharField(default='linear-gradient(135deg, #e0f7ff 0%, #b3e5fc 100%)', help_text='CSS gradient for icon background', max_length=200)),
                ('icon_color', models.CharField(default='#0288d1', help_text='Icon color (hex code)', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)')),
            ],
            options={
                'verbose_name': 'Category Icon',
                'verbose_name_plural': 'Category Icons',
                'ordering': ['order', 'id'],
            },
        ),
    ]
