# Generated by Django 6.0.1 on 2026-01-29 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0026_categoryicon'),
    ]

    operations = [
    ]
