# Generated by Django 5.2.9 on 2026-02-01 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0029_productstocknotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Brand name', max_length=100)),
                ('logo', models.ImageField(help_text='Brand logo image', upload_to='brand_partners/')),
                ('link_url', models.URLField(blank=True, help_text='Optional link URL', null=True)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('is_active', models.BooleanField(default=True, help_text='Show/hide brand')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Brand Partner',
                'verbose_name_plural': 'Brand Partners',
                'ordering': ['order', 'name'],
            },
        ),
    ]
