# Generated by Django 5.2.9 on 2026-02-01 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0030_brandpartner'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryicon',
            name='icon_image',
            field=models.ImageField(blank=True, help_text='Upload category icon image (PNG with transparent background recommended)', null=True, upload_to='category_icons/'),
        ),
        migrations.AlterField(
            model_name='categoryicon',
            name='icon_class',
            field=models.CharField(blank=True, help_text="FontAwesome icon class (e.g., 'fas fa-mobile-alt') - DEPRECATED: Use icon_image instead", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='categoryicon',
            name='icon_color',
            field=models.CharField(default='#0288d1', help_text='Icon color (hex code) - Only used for FontAwesome icons', max_length=20),
        ),
    ]
