# Generated by Django 5.2.9 on 2026-02-02 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0031_categoryicon_icon_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_to', models.EmailField(max_length=254)),
                ('email_type', models.CharField(choices=[('ORDER_CONFIRMATION', 'Order Confirmation'), ('ORDER_STATUS_UPDATE', 'Order Status Update'), ('DELIVERY_REMINDER', 'Delivery Reminder'), ('REVIEW_REQUEST', 'Review Request'), ('PRICE_ALERT', 'Price Alert'), ('PROMOTIONAL', 'Promotional Email')], max_length=30)),
                ('subject', models.CharField(max_length=300)),
                ('sent_successfully', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='Hub.order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Log',
                'verbose_name_plural': 'Email Logs',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.IntegerField(default=0, help_text='Total points earned')),
                ('points_used', models.IntegerField(default=0, help_text='Points redeemed')),
                ('points_available', models.IntegerField(default=0, help_text='Available points to use')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_points', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Loyalty Points',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('ORDER_PLACED', 'Order Placed'), ('ORDER_CONFIRMED', 'Order Confirmed'), ('ORDER_SHIPPED', 'Order Shipped'), ('ORDER_DELIVERED', 'Order Delivered'), ('PRICE_DROP', 'Price Drop Alert'), ('STOCK_AVAILABLE', 'Stock Available'), ('RETURN_APPROVED', 'Return Approved'), ('REFUND_PROCESSED', 'Refund Processed'), ('POINTS_EARNED', 'Loyalty Points Earned'), ('SPECIAL_OFFER', 'Special Offer')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, help_text='URL to related page', max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PointsTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('transaction_type', models.CharField(choices=[('EARNED', 'Points Earned'), ('REDEEMED', 'Points Redeemed'), ('EXPIRED', 'Points Expired'), ('ADJUSTED', 'Manual Adjustment')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_transactions', to='Hub.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Points Transaction',
                'verbose_name_plural': 'Points Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('reason', models.CharField(choices=[('DEFECTIVE', 'Defective/Damaged Product'), ('WRONG_ITEM', 'Wrong Item Received'), ('NOT_AS_DESCRIBED', 'Not As Described'), ('SIZE_ISSUE', 'Size/Fit Issue'), ('QUALITY_ISSUE', 'Quality Issue'), ('CHANGED_MIND', 'Changed Mind'), ('OTHER', 'Other Reason')], max_length=30)),
                ('description', models.TextField(help_text='Detailed description of the issue')),
                ('images', models.ImageField(blank=True, help_text='Upload product images', null=True, upload_to='returns/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PICKUP_SCHEDULED', 'Pickup Scheduled'), ('PICKED_UP', 'Picked Up'), ('REFUND_INITIATED', 'Refund Initiated'), ('REFUND_COMPLETED', 'Refund Completed')], default='PENDING', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal admin notes')),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('refund_method', models.CharField(blank=True, help_text='Bank transfer, Original payment method, etc.', max_length=50)),
                ('pickup_date', models.DateTimeField(blank=True, null=True)),
                ('refund_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='Hub.order')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='Hub.orderitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Return Request',
                'verbose_name_plural': 'Return Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WishlistPriceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('target_price', models.DecimalField(blank=True, decimal_places=2, help_text='Alert when price drops below this', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notified', models.BooleanField(default=False, help_text='Has user been notified of price drop?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_alerts', to='Hub.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wishlist Price Alert',
                'verbose_name_plural': 'Wishlist Price Alerts',
                'ordering': ['-created_at'],
            },
        ),
    ]
