# Generated by Django 5.2.9 on 2026-02-02 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0032_emaillog_loyaltypoints_notification_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='approval_notes',
            field=models.TextField(blank=True, help_text='Admin notes for approval/rejection'),
        ),
        migrations.AddField(
            model_name='order',
            name='approval_status',
            field=models.CharField(choices=[('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('AUTO_APPROVED', 'Auto Approved')], default='PENDING_APPROVAL', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='is_suspicious',
            field=models.BooleanField(default=False, help_text='Flagged as potentially fraudulent'),
        ),
        migrations.AddField(
            model_name='order',
            name='risk_score',
            field=models.IntegerField(default=0, help_text='Fraud risk score (0-100)'),
        ),
        migrations.AddField(
            model_name='order',
            name='suspicious_reason',
            field=models.TextField(blank=True, help_text='Reason for flagging as suspicious'),
        ),
    ]
