# Generated by Django 5.2.9 on 2026-02-02 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0033_order_approval_notes_order_approval_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='VibeMall', help_text='Website name displayed across the site', max_length=100)),
                ('site_logo', models.ImageField(blank=True, help_text='Main logo (recommended: 150x50px PNG with transparent background)', null=True, upload_to='site/')),
                ('site_favicon', models.ImageField(blank=True, help_text='Favicon icon (recommended: 32x32px PNG)', null=True, upload_to='site/')),
                ('tagline', models.CharField(blank=True, help_text='Website tagline/slogan', max_length=200)),
                ('contact_email', models.EmailField(default='support@vibemall.com', max_length=254)),
                ('contact_phone', models.CharField(default='+91 1234567890', max_length=20)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('admin_logo', models.ImageField(blank=True, help_text='Admin panel logo (recommended: 120x40px)', null=True, upload_to='site/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
