# Generated by Django 5.2.9 on 2026-02-02 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0035_sitesettings_site_name_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='is_auto_generated',
            field=models.BooleanField(default=False, help_text='Auto-generated review by system'),
        ),
    ]
