# Generated by Django 5.2.9 on 2026-02-03 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0036_productreview_is_auto_generated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
