# Generated by Django 5.2.9 on 2026-02-04 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0039_add_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminemailsettings',
            name='admin_email',
            field=models.EmailField(default='info.vibemall@gmail.com', help_text='Email to receive order notifications', max_length=254),
        ),
        migrations.CreateModel(
            name='MainPageProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('category1', 'Category 1'), ('category2', 'Category 2'), ('category3', 'Category 3'), ('category4', 'Category 4')], max_length=20)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_page_items', to='Hub.product')),
            ],
            options={
                'verbose_name_plural': 'Main Page Products',
                'ordering': ['category', 'order'],
                'unique_together': {('product', 'category')},
            },
        ),
    ]
