# Generated by Django 6.0.1 on 2026-02-07 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0044_alter_returnrequest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=34),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='bank_ifsc',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
