# Generated by Django 6.0.1 on 2026-02-07 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0045_returnrequest_bank_account_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='upi_id',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
