# Generated by Django 5.2 on 2026-02-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0046_returnrequest_upi_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='upi_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
